### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Burla4enko/grid-template-init-project#1]
Наведение не отрабатывается
![image](https://user-images.githubusercontent.com/8464662/52058014-3b6b5c00-256f-11e9-9952-215482fa358e.png)

размеры не соответствуют
![image](https://user-images.githubusercontent.com/8464662/52058143-91d89a80-256f-11e9-95ab-e18a32105c53.png)
![image](https://user-images.githubusercontent.com/8464662/52058185-a1f07a00-256f-11e9-9817-95567a770fb0.png)

**Comment by Burla4enko** [comment]
Такие мелкие ошибки...
Сейчас все быстренько исправим =)
